- name: Stop services
  command: 'service {{ item }} stop'
  with_items:
    - 'docker'
  ignore_errors: yes
  when: PROVISION.docker == 1

- name: Create mountpoint (/mnt/data)
  file:
    path:  /mnt/data
    state: directory
    owner: root
    group: root
    mode:  0755

- name: "Setup mounting for /dev/{{ SERVER.data.partition }}"
  mount:
    name:  /mnt/data
    src:   '/dev/{{ SERVER.data.partition }}'
    fstype: '{{ SERVER.data.filesystem }}'
    opts:   'defaults,nodev,nosuid,noatime,nodiratime,data=writeback,barrier=0,nobh'
    state:  present

- name: 'Mount /dev/{{ SERVER.data.partition }}'
  mount: name=/mnt/data src='/dev/{{ SERVER.data.partition }}' fstype='{{ SERVER.data.filesystem }}' state=mounted

#############################
# Docker
#############################

- stat: path=/mnt/data/docker/
  register: dockerdir

- name: Create docker storage
  shell: 'mkdir /mnt/data/docker && cp -a /var/lib/docker/* /mnt/data/docker'
  args:
    creates: '/mnt/data/docker/'
  when: PROVISION.docker == 1

- name: Setup rights for docker
  file:
    path:  /mnt/data/docker
    state: directory
    owner: root
    group: root
    mode:  0700
  when: PROVISION.docker == 1

- name: Setup mounting for docker
  mount:
    name:   /var/lib/docker/
    src:    /mnt/data/docker
    fstype: none
    opts:   'bind'
    state:  present
  when: PROVISION.docker == 1

- name: Mount docker
  mount:
    name:   /var/lib/docker/
    src:    /mnt/data/docker
    fstype: none
    opts:   'bind'
    state:  mounted
  when: PROVISION.docker == 1

- name: Start services
  command: 'service docker restart'
  ignore_errors: True
  when: PROVISION.docker == 1