- name: Generate ssh key
  user:
    name: '{{ ansible_user }}'
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519
    ssh_key_comment: '{{ ansible_user}}@{{ansible_host}}'
