- name: Check file incron.allow exist
  file: path=/etc/incron.allow state=touch mode=0644

- name: Enable incron usage for {{ ansible_user }}
  lineinfile:
    dest:   /etc/incron.allow
    regexp: '{{ ansible_user }}'
    line:   '{{ ansible_user}}'
  notify:
    - Restart incron

# name: Load incrontab
- raw: echo "" > /tmp/user.incrontab
- raw: echo "/home/{{ ansible_user }}/.ssh/config.user    IN_MODIFY,IN_DELETE,IN_CREATE,IN_NO_LOOP /usr/local/bin/ct user:rebuildsshconfig" >> /tmp/user.incrontab
- raw: echo "/home/{{ ansible_user}}/.ssh/config.default IN_MODIFY,IN_DELETE,IN_CREATE,IN_NO_LOOP /usr/local/bin/ct user:rebuildsshconfig" >> /tmp/user.incrontab
- raw: su {{ ansible_user }} -c "incrontab /tmp/user.incrontab"
- raw: rm -f /tmp/user.incrontab
