---

- name: Install monit pkg [Debian]
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - monit
    - logwatch
  when: ansible_os_family == 'Debian'

- name: Install monit pkg [RedHat]
  yum:
    name:   '{{ item }}'
    state: present
  with_items:
    - monit
    - logwatch
  when: ansible_os_family == 'RedHat'
