---
- name: Ensure git's dependencies are installed (RedHat).
  yum: "pkg={{ item }} state=installed"
  with_items:
    - gettext-devel
    - expat-devel
    - curl-devel
    - zlib-devel
    - perl-devel
    - openssl-devel
    - subversion-perl
    - make
    - gcc
  when: ansible_os_family == 'RedHat'

- name: Ensure git's dependencies are installed (Debian).
  apt: "pkg={{ item }} state=installed"
  with_items:
    - libcurl4-gnutls-dev
    - libexpat1-dev
    - gettext
    - libssl-dev
    - build-essential
    - gcc
  when: ansible_os_family == 'Debian'

- name: Get installed version
  command: git --version
  changed_when: false
  failed_when: false
  register: git_installed_version

- name: Force git install if the version numbers do not match
  set_fact:
    git_reinstall_from_source: true
  when: 'GIT.install_from_source_force_update and (git_installed_version|success and (git_installed_version.stdout | regex_replace("^.*?([0-9\.]+)$", "\\1") | version_compare(GIT.version, operator="!=")))'

- name: Download git.
  get_url:
    url: "https://www.kernel.org/pub/software/scm/git/git-{{ GIT.version }}.tar.gz"
    dest: "{{ GIT.workspace }}/git-{{ GIT.version }}.tar.gz"
  when:  git_installed_version|failed or git_reinstall_from_source

- name: Expand git archive.
  unarchive:
    src: "{{ GIT.workspace }}/git-{{ GIT.version }}.tar.gz"
    dest: "{{ GIT.workspace }}"
    creates: "{{ GIT.workspace }}/git-{{ GIT.version }}/README"
    copy: no
  when:  git_installed_version|failed or git_reinstall_from_source

- name: Build git.
  command: >
    make prefix={{ GIT.install_path }} {{ item }}
    chdir={{ GIT.workspace }}/git-{{ GIT.version }}
  with_items:
    - all
    - install
  when:  git_installed_version|failed or git_reinstall_from_source
  become: yes

- name: Remove git source
  command: >
    rm -rf {{ GIT.workspace }}/git-{{ GIT.version }}.tar.gz
    rm -rf {{ GIT.workspace }}/git-{{ GIT.version }}
  when:  git_installed_version|failed or git_reinstall_from_source
  ignore_errors: yes
