---

- name: Ensure git is installed (RedHat).
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: "{{ GIT.enablerepo }}"
  with_items: "{{ GIT.packages }}"
  when: (GIT.install_from_source == false) and (ansible_os_family == 'RedHat')
  tags:
    - bootstrap

- name: Update apt cache (Debian).
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'
  tags:
    - bootstrap

- name: Ensure git is installed (Debian).
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ GIT.packages }}"
  when: (GIT.install_from_source == false) and (ansible_os_family == 'Debian')
  tags:
    - bootstrap

# Install git from source when GIT.install_from_source is true.
- include: install-from-source.yml
  when: GIT.install_from_source == true
  tags:
    - bootstrap
