- name: Add tmp cleanup at reboot [Debian]
  lineinfile:
    dest:   '/etc/default/rcS'
    regexp: '^#?TMPTIME=0'
    line:   'TMPTIME=0'
  when: ansible_os_family == 'Debian'

- name: Disable blank console screensaver
  lineinfile:
    dest:   '/etc/default/grub'
    regexp: '{{ item.regexp }}'
    line:   '{{ item.line }}'
  with_items:
   - { regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=', line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet consoleblank=0"' }
   - { regexp: '^GRUB_TIMEOUT=', line: 'GRUB_TIMEOUT=0' }
   - { regexp: '^GRUB_HIDDEN_TIMEOUT=', line: 'GRUB_TIMEOUT=0' }
  notify:
    - Update grub
  when: ansible_os_family == 'Debian'
