- name: zsh - git repo for oh-my-zsh fork
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ home_dir }}/.oh-my-zsh"
  ignore_errors: True

- name: Creating new "{{ home_dir }}/.zshrc"
  action: 'shell cp {{ home_dir }}/.oh-my-zsh/templates/zshrc.zsh-template {{ home_dir }}/.zshrc'
  args:
    creates: '{{ home_dir }}/.zshrc'